baseURL = 'https://timwalter.github.io/'
languageCode = 'en-gb'
title = 'Tim Walter'
theme = 'ananke'
[caches]
  [caches.images]
    dir = ':cacheDir/images'


[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'